default: &default
  slack_token: token_here
  slack_channel: channel_name # or '@user'
  data_path: /path/to/data
  emb_path: /path/to/embeddings
  log_path: /logs/will/be/here
  model_path: /model/oarameters/will/save/here

debug:
  <<: *default

production:
  <<: *default